# Copyright 2024-2025 Amazon.com, Inc. or its affiliates.

name: osml_data_intake
channels:
  - conda-forge
dependencies:
  - conda-forge::boto3=1.40.13
  - conda-forge::gdal=3.11.3
  - conda-forge::proj=9.6.2
  - conda-forge::pip=25.2
  - pip:
      - osml-imagery-toolkit==1.4.2
      - stac_fastapi.types==6.0.0
      - stac_fastapi.opensearch==6.3.0
      - pystac[validation]==1.8.3
      - jsonschema>=4.0.1,<4.18
      - python-json-logger==3.3.0
